### ISSUE TITLE
detect multi hands

### ISSUE THREAD

**Issue by lilyswang** [metalwhale/hand_tracking#1]
Hi,thanks for you share about hand_tracking ,it's a nice job.
 I want to consult that how could we detect multi hands and these points?
Thx!

**Comment by metalwhale** [comment]
Hi @lilyswang, thank you for your interest in my work.
I'm not sure about multi hands tracking job but you can follow this [issue](https://github.com/google/mediapipe/issues/32) on official [Mediapipe](https://mediapipe.dev) repo.
Programmatically you can try to do it now with some self-research, or waiting for them to release the  example with the new features once ready, it's up to you 🤗.

**Comment by lilyswang** [comment]
Ok,thanks for your nice work again🤗
